# demo-accounts.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: team5-eureka-client-account
  namespace: under76-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team5-eureka-client-account
  template:
    metadata:
      labels:
        app: team5-eureka-client-account
    spec:
      containers:
      - name: team5-eureka-client-account
        image: k8s-vga-worker1:5000/img-team5-eureka-client-account:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: team5-eureka-client-account
  namespace: under76-test
spec:
  selector:
    app: team5-eureka-client-account
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      nodePort: 30299
  type: NodePort
